### ISSUE TITLE
How to access raw pixel values?

### ISSUE THREAD

**Issue by Kesanov** [openrndr/openrndr-guide#76] opened 2021-03-13 10:51 UTC
I have a quite specific usecase, where I need to compute similarity between two images:

```kotlin
var similarity = 0.0
for (x in 0..width) for (y in 0..height) {
  euclid_distance(image0.rgb(x,y), image1.rgb(x,y)) // image 0,1 are composite shapes or svg
}
return similarity / width*height
```

I wasn't able to find `.rgb(x,y)` in the guide or the API, is there anything like it? 
Moreover, I need this operation to be super fast, so the call to `.rgb` should have zero overhead. Also I wonder if `openrdnr` could allow me to implement it on GPU to get some further speedups.

**Comment by hamoid** [comment] 2021-03-13 12:27
Hi! :)

If it's similarity pixel by pixel, can't you just subtract one image from the other to obtain the difference in the GPU?

For the CPU approach find `shadow` at https://guide.openrndr.org/#/06_Advanced_drawing/C0_Colorbuffers?id=color-buffer-shadows

**Comment by Josef-Vonasek** [comment] 2021-03-13 14:47
@hamoid Hi, thanks for quick reply. 

The `shadow` approach looks good, but I am not sure how can I obtain `shadow` of `Shape`. 

Using `subtract` looks like a good direction, but I also need to aggregate the difference in pixels into one value.

At high level it could look like this: 
```kotlin
(img0 - imgb).mapPixels{ sqrt(it.red^2 + it.green^2 + it.blue^2) }.sumPixels()
```
I think all of those operations can be performed on GPU efficiently (it's just matrix manipulation).

One more question. Is it possible to obtain a readonly crop of an image (basically a subimage), that doesn't copy the pixels of the original when created?

**Comment by hamoid** [comment] 2021-03-13 17:07
Hi, if you are drawing shapes then you should first draw them on a render target (maybe using `drawer.isolatedWithTarget(rt)`). The `renderTarget` has a `colorBuffer` attached to it and you can read its `shadow`.

What comes to mind is using a shader. The shader would input two uniforms (two images). 
The render target could be a high precision one (using `ColorType.FLOAT32` for example) and maybe ColorFormat.R for monochrome. I guess it's possible to have RGB inputs but R output. 
Then I would calculate the difference of R, G and B and store the result in the R channel, producing a monochrome image of the difference.
The final step is to add all the R values together. The easy approach is to download the shadow and iterate over every pixel. I think it should be rather fast, but it will depend on the buffer size.

Adding the values together in the GPU I think is more tricky, but I don't know how to do that. I think one way would be to do it in multiple passes. Something like adding every 8 pixels horizontally together, then adding 8 pixels from the previous result (vertically) together, etc, and doing that a few time until you obtain one value. Something like traversing a tree from the branches to the core. 

Another option in the GPU would be in a compute shader (not doable on Mac).

I think I would start with the naive approach, see how slow it is, then try optimize it. How fast does it need to be?

**Comment by Josef-Vonasek** [comment] 2021-03-13 18:10
I use it as a loss function in my ML project, so I basically need it to be fast as possible.

I imagine the `sum` could use similar algorithm as `blur`, since it is basically a convolution over the whole image.

**Comment by hamoid** [comment] 2021-03-13 18:12
Exactly, and blur is often implement as a multipass thing, alternating  between horizontal and vertical blur.

**Comment by Josef-Vonasek** [comment] 2021-03-13 18:20
Ok, I will look into the blur source code and implement something similar. 

One more thing. How could you compute `sum` of neighboring pixels with shader? I thought shader operates with one pixel at a time. And why does it not work on Mac?

**Comment by Josef-Vonasek** [comment] 2021-03-14 16:37
I have successfully tested an implementation on CPU that uses  `renderTarget` `.shadow[x,y]` and.

To my surprise, it ran 100x - 1000x slower than my second implementation that used builtin `BufferedImage` and `.getRGB(x,y)`!

I wonder if it's caused by th overhead of passing data between GPU and CPU with `.shadow` or something else.

**Comment by hamoid** [comment] 2021-03-14 16:37
A shader can have inputs (uniforms). It could have two such uniforms for two input images. You can be working on a shader for a buffer that is smaller than those uniforms. For example:

Original images are both 1000x500.
Current image is 1000x1. The shader will loop over 500 pixels vertically and add them all together. I don't know if it's a good idea to go from 500 to 1 or is it better to go from 1000x500 to 1000x16, so you are splitting the task into 16 smaller ones instead of 1 with a huge loop. But if you go from 1000 to 16, then you need a second pass to go from 16 to 1.
Once you have the 1000x1 result, you can go horizontally to add all those pixels. Again, it can be done in one or more passes.

If doing it in two passes a good width and height might be something close to the square root of the width and the height

Fragment and vertex shaders do work on Mac, but compute shaders require an opengl version that is not available on Mac, as mentioned [here](https://guide.openrndr.org/#/11_Advanced_Topics/C06_Compute_shaders).

**Comment by hamoid** [comment] 2021-03-14 16:38
About the performance of your test: did you call `shadow.download()`?

**Comment by Josef-Vonasek** [comment] 2021-03-14 16:48
The code looks like this:

```kotlin
        var sum= 0.0
        val s0 = rt0.colorBuffer(0).shadow.apply{download()}
        val s1 = rt1.colorBuffer(0).shadow.apply{download()}
        for (y in 0..height) {
            for (x in 0..width) {
                sum+= sqrt((s0[x,y].r-s1[x,y].r).pow2 + (s0[x,y].g-s1[x,y].g).pow2 + (s0[x,y].b-s1[x,y].b).pow2)
            }
        }
        d0.destroy()
        d1.destroy()
        d2.destroy()
        return soucet
```

**Comment by hamoid** [comment] 2021-03-14 17:00
I would try
```
val p0 = s0[x,y]
val p1 = s1[x,y]
var rd = p0.r-p1.r
val gd = p0.g-p1.g
val bd = p0.b-p1.b
sum+= sqrt(rd*rd + gd*gd + bd*bd)
```

do you need that sqrt? removing it also would make it faster... But as you need it really fast, a shader might be the better option.

**Comment by hamoid** [comment] 2021-03-14 17:08
> It takes ~24 secs on my machine.

Right, but you are creating and destroying 1000 render targets! And downloading them from GPU to CPU 1000 times! :-)

Ideally you create them once and reuse them. Is that possible? Uploading and downloading stuff from the GPU is not so fast. What is fast is the calculations performed in the GPU.

**Comment by Josef-Vonasek** [comment] 2021-03-14 17:29
I have added benchmarks with buffered image. Even though it is 10x faster, it is not 100x faster, so I have a bug somewhere.

On render targets: In other words, composition of shapes is fast, composition of render targets is slow. Looking at the API, blur requires a render target first, so I wonder if it will be even faster than doing it on CPU directly.

**Comment by hamoid** [comment] 2021-03-15 16:43
It sounds like you need to profile all the steps. How long it takes to load an image, to send it to the gpu, to download the result, to calculate the sum on CPU, to the same in the GPU, etc. It will also depend on the image width, height, file format (if it's not generated), bit depth.

If you calculate the sum in the GPU you just need to download 1 float which should be fast. But upload time is still there.

**Comment by hamoid** [comment] 2022-04-17 08:51
Closing as it's not an actionable issue with the guide (even if an interesting topic :-)

For discussions: https://github.com/openrndr/openrndr/discussions or https://openrndr.discourse.group/

**Closed by hamoid** 2022-04-17 08:51 UTC
